### ISSUE TITLE
Problemen complilation 

### ISSUE THREAD

**Issue by ceaguilera** [inthegarage/angular-pin#1]
hi, i have problem,

Failed to compile.

./node_modules/ng-pin/fesm2015/ng-pin.js 89:138-156
"export 'ɵɵFactoryTarget' (imported as 'i0') was not found in '@angular/core'

error to complile

**Comment by inthegarage** [comment]
You will need to use ng 12, if its the latest version. If that doesn't
help, then raise an issue.

**Comment by inthegarage** [comment]
@ceaguilera Please follow the stackblitz provided:

https://stackblitz.com/edit/angular-ivy-wqhpxn

Note the current library only supports ng12 and above. I don't intend to support very old versions of Angular. If you issue continues to surface then provide an example stackblitz or codepen etc.
